// Generated by `npm run sfx` — don't edit. Use with shared(SHARED_SFX["whoosh-up"].src).
// peak = seconds from the start of the file to its loudest moment: pass it as a cue's `peak`
// and the cue's `at` becomes the frame where that loudest moment lands.
export const SHARED_SFX = {
  "air-bed": { src: "sfx/air-bed.wav", seconds: 31.0, peak: 16.098 },
  "riser": { src: "sfx/riser.wav", seconds: 1.8, peak: 1.367 },
  "shimmer": { src: "sfx/shimmer.wav", seconds: 1.6, peak: 0.844 },
  "sub-hit": { src: "sfx/sub-hit.wav", seconds: 1.4, peak: 0.011 },
  "sub-soft": { src: "sfx/sub-soft.wav", seconds: 1.0, peak: 0.004 },
  "swish": { src: "sfx/swish.wav", seconds: 0.45, peak: 0.281 },
  "tick-low": { src: "sfx/tick-low.wav", seconds: 0.07, peak: 0.003 },
  "tick": { src: "sfx/tick.wav", seconds: 0.07, peak: 0.003 },
  "whoosh-down": { src: "sfx/whoosh-down.wav", seconds: 0.8, peak: 0.213 },
  "whoosh-up": { src: "sfx/whoosh-up.wav", seconds: 0.9, peak: 0.614 },
} as const;
